name: λ””μμΈ
description: νΌλΈ”λ¦¬μ‹±/CSS μμ •
title: '[design] '
body:
  - type: markdown
    attributes:
      value: |
        ## π“ νΌλΈ”λ¦¬μ‹± ν•  λ‚΄μ© or μμ •ν•  λ‚΄μ©

        - μ•„λ μ…λ ¥ ν•„λ“μ— λ³€κ²½ν•  λ‚΄μ©μ„ μμ„Έν μ‘μ„±ν•΄μ£Όμ„Έμ”.

  - type: textarea
    id: details
    attributes:
      label: λ³€κ²½ μ‚¬ν•­
      description: μ–΄λ–¤ λ””μμΈμ„ λ³€κ²½ν•κ±°λ‚ νΌλΈ”λ¦¬μ‹±ν• μ§€ μμ„Έν μ μ–΄μ£Όμ„Έμ”.
      placeholder: μ) λ²„νΌ μƒ‰μƒμ„ νλ€μƒ‰μ—μ„ μ΄λ΅μƒ‰μΌλ΅ λ³€κ²½
    validations:
      required: false
